on:
    pull_request
    # pull_request:
    #     paths:
    #         - "../front_end/src"
# default:
#     run:
#         working_directory: ./front_end/src
jobs:
    run-test:
        name: front_build_test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # - name: package install
            #   run: npm install
            #   working_directory: ./front_end/src
            - name: install
              run: cd front_end/src && ls -a && npm install
            - uses: actions/cache@v2
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
            - name: build
              run: cd front_end/src && ls -a && npm run build
